version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "12:45"
    assignees:
      - "monikavalkova"
    groups:
      all-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "dependabot"
